### ISSUE TITLE
Failed to connect to api port 3000: Connection refused

### ISSUE THREAD

**Issue by luckisoff** [solution-libre/docker-socioboard#1]
![image](https://user-images.githubusercontent.com/8510066/111627300-04239c00-8817-11eb-84f7-89aeb063abcb.png)
![image](https://user-images.githubusercontent.com/8510066/111627449-2a493c00-8817-11eb-8d25-8ab294ae8d91.png)

Not able to connect from container to node apis.

**docker logs socioboard_api_1**
`folder
folder
folder
folder
==> /opt/socioboard-api/notification/public/logs/library20210318.log <==

==> /opt/socioboard-api/notification/public/logs/services20210317.log <==
      column: 10,
      file: 'internal/modules/cjs/loader.js',
      function: 'Module._extensions..js',
      line: 1092,
      method: '.js',
      native: false
    }
  ],
  timestamp: '2021-03-17T17:15:59.847Z'
}

==> /opt/socioboard-api/notification/public/logs/services20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:22.365Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:22.366Z'
}

==> /opt/socioboard-api/feeds/public/logs/feed20210317.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:16:03.472Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:16:03.478Z'
}

==> /opt/socioboard-api/feeds/public/logs/feed20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:23.628Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:23.632Z'
}

==> /opt/socioboard-api/feeds/public/logs/library20210317.log <==

==> /opt/socioboard-api/feeds/public/logs/library20210318.log <==

==> /opt/socioboard-api/feeds/public/logs/user20210317.log <==

==> /opt/socioboard-api/feeds/public/logs/user20210318.log <==

==> /opt/socioboard-api/publish/public/logs/library20210317.log <==

==> /opt/socioboard-api/publish/public/logs/library20210318.log <==

==> /opt/socioboard-api/publish/public/logs/publish20210317.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:24:27.330Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:24:27.334Z'
}

==> /opt/socioboard-api/publish/public/logs/publish20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:22.333Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:22.340Z'
}

==> /opt/socioboard-api/publish/public/logs/user20210317.log <==

==> /opt/socioboard-api/publish/public/logs/user20210318.log <==

==> /opt/socioboard-api/user/public/logs/library20210316.log <==

==> /opt/socioboard-api/user/public/logs/library20210317.log <==

==> /opt/socioboard-api/user/public/logs/library20210318.log <==

==> /opt/socioboard-api/user/public/logs/user20210316.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-16T22:16:42.969Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-16T22:16:42.970Z'
}

==> /opt/socioboard-api/user/public/logs/user20210317.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:24:59.921Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-17T17:24:59.921Z'
}

==> /opt/socioboard-api/user/public/logs/user20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:23.572Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T11:44:23.572Z'
}
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
(node:68) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:68) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.

==> /opt/socioboard-api/notification/public/logs/services20210318.log <==
{
  message: 'Cron setup intialized for twitter insights services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:16.933Z'
}
{
  message: 'Cron setup completed for twitter insights services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:16.950Z'
}
{
  message: 'Cron setup intialized for teams report insights services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:16.951Z'
}
{
  message: 'Cron setup completed for teams report insights services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:16.951Z'
}
{
  message: 'Cron setup intialized for mail services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:17.176Z'
}
{
  message: 'Cron setup completed for mail services...',
  level: 'info',
  timestamp: '2021-03-18T12:19:17.183Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:17.280Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:17.281Z'
}
(node:76) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:76) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
[nodemon] clean exit - waiting for changes before restart

==> /opt/socioboard-api/publish/public/logs/publish20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:17.859Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:17.866Z'
}
(node:69) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:69) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
[nodemon] clean exit - waiting for changes before restart
(node:82) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:82) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.

==> /opt/socioboard-api/feeds/public/logs/feed20210318.log <==
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:18.656Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:18.661Z'
}

==> /opt/socioboard-api/user/public/logs/user20210318.log <==
{
  message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2021-03-18T12:19:18.729Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:18.801Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:19:18.802Z'
}
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
(node:128) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:128) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
{
  message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2021-03-18T12:23:59.752Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:23:59.820Z'
}
{
  message: 'Mongo issues : Unescaped at-sign in authority section',
  level: 'error',
  timestamp: '2021-03-18T12:23:59.821Z'
}
`
**docker logs socioboard_web_1**
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.144.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.144.5. Set the 'ServerName' directive globally to suppress this message
[Thu Mar 18 12:19:14.332503 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.1.33 configured -- resuming normal operations
[Thu Mar 18 12:19:14.332793 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'`

**Comment by FlorentPoinsaut** [comment]
Hello,
I don't really understand why your app try to contact your API with the port 3000 and not 3001.
But, I just fix API and web images with this commit https://github.com/solution-libre/docker-socioboard/commit/54ad163e2179939d42a73edf4e1dd7e97d556b2d
Could you try with this fix please?
Regards,

**Comment by luckisoff** [comment]
> Hello,
> I don't really understand why your app try to contact your API with the port 3000 and not 3001.
> But, I just fix API and web images with this commit [54ad163](https://github.com/solution-libre/docker-socioboard/commit/54ad163e2179939d42a73edf4e1dd7e97d556b2d)
> Could you try with this fix please?
> Regards,

Hello,
thanks for the reply port 3000 is because the .env file in laravel has api_url as http://api:3000 and also the node api is running with port 3000. BTW I had already done that. I had removed these lines because they were creating error but may be I had also removed `&` along. I will try with this fix.

**Comment by luckisoff** [comment]
> Hello,
> I don't really understand why your app try to contact your API with the port 3000 and not 3001.
> But, I just fix API and web images with this commit [54ad163](https://github.com/solution-libre/docker-socioboard/commit/54ad163e2179939d42a73edf4e1dd7e97d556b2d)
> Could you try with this fix please?
> Regards,
Still its not working.
![image](https://user-images.githubusercontent.com/8510066/111735962-092f2c80-88a5-11eb-8145-f5df99f464a9.png)

`.env` file
![image](https://user-images.githubusercontent.com/8510066/111736398-db96b300-88a5-11eb-83d1-8c175ee14390.png)
api logs
![image](https://user-images.githubusercontent.com/8510066/111736478-01bc5300-88a6-11eb-800c-3d27433cc2a0.png)
web logs
![image](https://user-images.githubusercontent.com/8510066/111736521-16005000-88a6-11eb-97b2-da3b420a5d1a.png)
Thanks,

**Comment by FlorentPoinsaut** [comment]
Hello,
OK I found the problem and I fixed it.
Could you try again with this changes: https://github.com/solution-libre/docker-socioboard/commit/48cc2450e506ab1459d88e37d6d33d38af1e8c50 ?
Regards,

**Comment by FlorentPoinsaut** [comment]
Hello,
Since there is no answer, I close this ticket. Feel free to ask to re-open it.
Regards
