### ISSUE TITLE
When reverse proxying I get mixed content errors

### ISSUE THREAD

**Issue by kenjibailly** [solution-libre/docker-socioboard#4]
CSS files and what not aren't loading, because they are pulled from http instead of https.

![image](https://user-images.githubusercontent.com/9883910/162004708-24a85ad9-b38d-44b9-9a38-3579003200b8.png)

I thought the APP_URL in the .env file in web should make sure this is https aka:
```
APP_URL=https://socioboard.mindglowing.art/
```

Checked, everything seems to be filled in correctly afaik, new to socioboard.

Any idea how I can fix this?
I tried contacting ppl from swag (my reverse proxy) aka nginx reverse proxying, but they told me it's a problem within socioboard where I need to tell it to use https instead of http. No idea where I could make sure it does this though.

Any idea's?

My nginx reverse proxy:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name socioboard.mindglowing.art;
    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app socioboard_web;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_set_header    X-Forwarded-Proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**Comment by kenjibailly** [comment]
Fixed this issue by enabling HTTPS using the documentation in Step 12
https://www.linuxbabe.com/ubuntu/install-socioboard-on-ubuntu-20-04 

Changing my nginx reverse proxy to upsream_port 443 and proto to https

**Comment by kenjibailly** [comment]
I recreated the container and can't seem to enable HTTPS anymore.
I get this error when trying to certbot apache:

```
http-01 challenge for socioboard.mindglowing.art
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: socioboard.mindglowing.art
   Type:   unauthorized
   Detail: Invalid response from
   https://socioboard.mindglowing.art/.well-known/acme-challenge/0dxG86m8klu3h_PwrwI1siRiyTiYnRf_BgEG2De299Y
   [***.***.**.***]: 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
   ```
   
   I tried a bunch of things, but I keep running into the same error. Not sure how to fix this.

**Comment by kenjibailly** [comment]
Not sure what the issue was. Couldn't get it back to work with certbot.
I was able to however manually add an apache cert and enable https, which solved the issue again.

Ref: https://techexpert.tips/apache/enable-https-apache/

**Comment by ghost** [comment]
Add 
`ASSET_URL=https://socioboard.mindglowing.art/`
